FROM golang:1.12rc1-alpine3.9

WORKDIR /src

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

COPY go.mod .
COPY go.sum .

RUN go mod download

# Inlcude files
ADD . .

# Building app
RUN go build -o goapp && cp goapp /